[package]
name = "mod-manager"
version = "0.1.0"
edition = "2021"

[dependencies.gtk]
package = "gtk4"
version = "0.6.6"
features = ["v4_10"]

[dependencies.adw]
package = "libadwaita"
version = "0.4.4"
features = ["v1_3"]
